### ISSUE TITLE
Release v0.2-alpha.2

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#56]
Gotta get another release out!

- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/34 - Hythloth Fix
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/46 - Spoiler Log
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/48 - Start with quest items
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/47 - Starting virtues
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/45 - U4 Remastered (C64)
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/43 - U4 v1.01 fixes
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/38 - Fix healer in Serpent's Hold
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/32 - Map randomization optional

Avatar.exe changes
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/50 - Output randomizer flag values
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/44 - Decrease chance of sleep lock
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/42 - Hit Chance -> Apple II
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/41 - Fix Sacrifice - Last coin
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/29 - Set active player
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/57 - Diagonal attack

Integrated Avatar.exe changes
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/50
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/44
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/42
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/41
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/29
- [x] https://github.com/Fenyx4/U4DosRandomizer/issues/57

**Comment by Fenyx4** [comment]
It's done and out!
